"""Interface (Protocol) cho tung buoc AI cua pipeline. TranscriptionPipeline
(application/pipeline.py) chi phu thuoc vao cac Protocol nay, khong phu thuoc
truc tiep thu vien AI - cho phep inject fake adapter khi test (xem tests/fakes.py).

Moi adapter la mot context manager: __enter__ load model (GPU), __exit__ giai
phong VRAM (xem infrastructure/gpu.py) - phu hop rang buoc VRAM han che cua may
dev (docs/memory/dev-machine-rtx4050.md).
"""

from pathlib import Path
from typing import Protocol

from subtitle_pipeline.domain.models import SpeakerTurn, SubtitleSegment, TranscriptSegment


class Denoiser(Protocol):
    def __enter__(self) -> "Denoiser": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def denoise(self, input_path: Path, output_path: Path) -> None: ...


class Transcriber(Protocol):
    def __enter__(self) -> "Transcriber": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def transcribe(self, audio_path: Path) -> tuple[list[TranscriptSegment], str]: ...


class Aligner(Protocol):
    def __enter__(self) -> "Aligner": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def align(
        self, audio_path: Path, transcript: list[TranscriptSegment]
    ) -> list[SubtitleSegment]: ...


class Diarizer(Protocol):
    def __enter__(self) -> "Diarizer": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def diarize(self, audio_path: Path) -> list[SpeakerTurn]: ...


class Translator(Protocol):
    def __enter__(self) -> "Translator": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def translate(self, segments: list[SubtitleSegment]) -> list[SubtitleSegment]: ...


class VoiceSynthesizer(Protocol):
    def __enter__(self) -> "VoiceSynthesizer": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def synthesize(self, text: str, output_path: Path) -> None: ...
